### ISSUE TITLE
Main Page > ProfileView 다이어그램 수정

### ISSUE THREAD

**Issue by from97** [Matching42/Matching42-front#36]
## Description
ProfileView 다이어그램 (흐름도) 수정 및 부족한 부분 추가. (나중에 새로운 사람이 개발을 하더라도 다이어그램만 보고 어떻게 개발되었는지 파악할 수 있는 수준이어야 함. )

### Todo
- [x] ProfileView 다이어그램 수정

### Content
https://www.figma.com/file/mbK3OSgIcxHivBGrEfSrnH/Main-ProfileView?node-id=0%3A1

**Comment by seo2im** [comment]
확인 완료
