### ISSUE TITLE
다이어그램(흐름도) 수정

### ISSUE THREAD

**Issue by deathnet** [Matching42/Matching42-front#43]
### Team List
- headerTitle prop: 모든 Team 개수 추가
- Team Li에 onclick Link to detail 추가
### My Team
- Team Li에 onclick Link to detail 추가
### TeamLi
- TeamImg 컴포넌트 prop: intra_URL 대신 ID로 수정
### Subject dropdown
- 컴포넌트 추가
### Todo
- [x] 다이어그램(흐름도) 수정하기

**Comment by deathnet** [comment]
### 서버 요구 데이터

TeamListView: 
모든 팀 데이터(leaderId, memberId(팀에 소속된 멤버들 인트라 아이디), subject(팀이 진행중인 서브젝트), startDate, teamName, state(progress, wait, 등), notionLink, gitLink, 팀 해시태그),
모든 팀 개수

MyTeamListView:
소속 팀 데이터

**Comment by seo2im** [comment]
확인 완료
