### ISSUE TITLE
Main page 컴포넌트(ProfileView, MatchingStateView) 흐름도 작성

### ISSUE THREAD

**Issue by from97** [Matching42/Matching42-front#5]
- 흐름도
https://www.figma.com/file/MTpLN4vzOhAYMoorjHwPYA/Main-ProfileView-MatchingStateView?node-id=0%3A1

- HTML 구조
  ```html
  /* profile view */
  <ProfileView>
	  <title>
	  <description>
	  <userInfoList>
		  <userInfoListItem>level</userInfoListItem>
		  <userInfoListItem>blackhole</userInfoListItem>
	  </userInfoList>
  </ProfileView>
  
  /* matching state view */
  <MatchingStateView>
	  <matchingState />
	  <matchingStartButton />
  </MatchingStateView>
  ```

**Comment by seo2im** [comment]
1. HTML 구조와 흐름도의 component이름을 일치시켜 주세요
- HTML 구조도의 의미는 실제 HTML tag로 작성해달라는 뜻이 아닌 해당 큰 컴포넌트가 어떤 구성요소를 가지고 있는지 파악하는 문서입니다. 따라서 흐름도의 component와 이름이 다르면 해석에 어려움이 생겨요.
예 h2 => title로 변경(흐름도에 맞춰 변경)

2. info category보다는 실제 데이터(level, blackhole)로 적어주세요. 미정일 지라도 지금으로써 확정된 요소를 적당히 적어주시고 나중에 수정하면 됩니다. 

위 2사항 반영해서 수정 부탁드립니다

**Comment by from97** [comment]
수정했습니다 확인 부탁드려요!

**Comment by seo2im** [comment]
확인 완료
